module.exports = {
                alreadyExists : "User with same email or username already exists",
                registeredSuccessfully : "succesfully registered",
                internalServerError : "Internal Server Errror",   
                successfullyInsertedDatas : "Successfully inserted Datas",
                userNotFound : "User not found",
                usersFound : "Users Found",
                SUCCESS : "SUCCESS",
                BAD_REQUEST : "BAD REQUEST",
                

                passwordIncorrect : "username or password incorrect",
                uploadOneImageSuccessfully : "you have uploaded One image ",
                uploadedManyImagesSuccessfully : "you have uploaded following images ",
                uploadedImageFieldSuccessfully : "uploaded Fields Successfully",
                active : "is Active",
                deativatedSuccessfully : "is deactivated",
                activatedSuccessfully : 'successfully activated',
                deactivatedSuccessfully : 'successfully deactivated',
                deletedSuccessfully : "You Deleted ",
                deletedSuccessFully : "deleted Successfully",
                blockedSuccessfully : " blocked successfully",
                unblockedSuccessfully : "Unblocked successsfully",
                welcome : "WELCOME ",
                incorrectEmailString : "Incorrect Email String",
                verifiedSuceessfully : "you have successfully verified your account",
                emailNotVerified : "Your Email is not verified",
                phoneNotVerified : "Your Phone is not verified",
                accountNotVerified : "Your account is not verified",
                invalidOTP : "Invalid OTP",
                blockedByAdmin : "You are blocked by the admin",
                provideDetails : "provide your ",
                checkEmail : "please check your email to reset password",
                tokenExpired : "your token is expired",
                somethingWentWrong : "something went wrong",
                passwordChangedSuccessfully : "Password Changed successfully",
                passwordAndNewPasswordNotSame : "password and confirm password are not same",

                phone : "phone",
                email : "email",
                forgetPassword : "forgetPassword",
                verfyPhone : "verfyPhone",
                verifyEmail : "verifyEmail",
                
}