module.exports = {
  alreadyExists: "User with same email or username already exists",
  registeredSuccessfully: "succesfully registered",
  internalServerError: "Internal Server Errror",
  successfullyInsertedDatas: "Successfully inserted Datas",
  userNotFound: "User not found",
  usersFound: "Users Found",
  SUCCESS: "SUCCESS",
  BAD_REQUEST: "BAD REQUEST",
  UNAUTHORIZED_ACCESS: "UNAUTHOROIZED ACCESS",
  ACCESS_FORBIDDEN: "ACCESS FORBIDDEN",
  FETCHED_SUCCESSFULLY: "Fetched Successfully",
  passwordIncorrect: "username or password incorrect",
  uploadOneImageSuccessfully: "you have uploaded One image ",
  uploadedManyImagesSuccessfully: "you have uploaded following images ",
  uploadedImageFieldSuccessfully: "uploaded Fields Successfully",
  active: "is Active",
  deativatedSuccessfully: "is deactivated",
  activatedSuccessfully: "successfully activated",
  deactivatedSuccessfully: "successfully deactivated",
  deletedSuccessfully: "You Deleted ",
  deletedSuccessFully: "deleted Successfully",
  blockedSuccessfully: " blocked successfully",
  unblockedSuccessfully: "Unblocked successsfully",
  welcome: "WELCOME ",
  incorrectEmailString: "Incorrect Email String",
  verifiedSuceessfully: "you have successfully verified your account",
  emailNotVerified: "Your Email is not verified",
  phoneNotVerified: "Your Phone is not verified",
  accountNotVerified: "Your account is not verified",
  invalidOTP: "Invalid OTP",
  blockedByAdmin: "You are blocked by the admin",
  provideDetails: "provide your ",
  checkEmail: "please check your email to reset password",
  tokenExpired: "your token is expired",
  somethingWentWrong: "something went wrong",
  passwordChangedSuccessfully: "Password Changed successfully",
  passwordAndNewPasswordNotSame: "password and confirm password are not same",
  phone: "phone",
  email: "email",
  forgetPassword: "forgetPassword",
  verfyPhone: "verifyPhone",
  verifyEmail: "verifyEmail",
  resendOTP: "resendOTPForVerification",
  CheckYour: "To reset password Check Your",
  SUCCESS: "SUCCESS",
  CHECK_YOUR_OTP: "Please Check your OTP on ",
  ONLY_IMAGE_FILES: "Only .jpg .png or .jpeg format allowed",
  OTP: "Your OTP for Expandimo is",
  RESET_OTP: "Your Reset OTP for Expandimo is",
  RESEND_OTP: "Your resent OTP for Expandimo is",
  NO_DATA : "No data found",
  NO_SUB_CATEGORY : "No Subcategory found",
  SUBCATEGORY_ALREADY_EXISTS :"Subcategory already exists",
  NO_CATEGORY : "No Category found",
  CATEGORY_ALREADY_EXISTS : "category already exists",
  DEFAULT_BODY : "default body",
  NO_ADDRESS_FOUND : "NO ADDRESS FOUND",
  ACCOUNT_CREDENTIAL : "sendCredential",
  NO_PRODUCT_FOUND : "NO  PRODUCTS FOUND",
  PRODUCT_ALREADY_EXISTS : "Product Already exists",
  MERCHANT_NOT_FOUND : 'MERCHANT NOT FOUND',
  
};
